import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>

      <script src={`https://nkjtnhziifrnbrlivbeu.supabase.co/storage/v1/object/public/pricing_flows/snippets/exp_7pjuy2jsqm/ab-test.js`} defer async></script>
      </head>
     
      {/* <Script
  id="tooltip-script"
  src="https://priceflows-assets.blr1.digitaloceanspaces.com/template-script/dev/tooltip-script-6805f1c5dfd88619c2d92289.js"
  strategy="afterInteractive"
/> */}
      
      <body className={inter.className}>
      
        {children}
      
      </body>
    </html>
  );
}
